port: 2239
mysql-host: localhost
#192.168.1.15
mysql-user: root
mysql-password: 123456
mysql-database: full_db_htth
debug: false
exp: 20
serveradmin: false
max-ip-connection: 10
max-ccu: 500
credit : truongbk
# Sự kiện Trung Thu
event-trung-thu: true