port: 2239
mysql-host: localhost
#192.168.1.15
mysql-user: root
mysql-password: 123456
mysql-database: full_db_htth
debug: false
exp: 20
serveradmin: false
max-ip-connection: 10
max-ccu: 500
credit : truongbk
# Sự kiện Trung Thu
event-trung-thu: false
# Sự kiện Tết Nguyên Đán
event-tet: true
# Tỉ lệ EXP & EXP Skill sự kiện Server (x2 = 2)
rate-exp: 2
rate-exp-skill: 2